/**
 * @file    input.c
 * @author  Ricardo J. Furlan
 * @brief   Interface for input modules: USB or Mouse
 * @version 0.1
 * @date    2025-05-09 
 */

#include <stdio.h>
#include "pico/stdlib.h"
#include "input.h"
#include "../lib_bitdoglab/ads/ads.h"
#include "../lib_bitdoglab/buttons/buttons.h"


#define AD_VALUE_DOWN    1024
#define AD_VALUE_UP      3072
#define AD_SPEED_US    300000

static uint16_t last_x = 2048;
static uint16_t last_y = 2048;
static uint64_t t0 = 0;

/**
 * @brief Initializes: ADs for acquiring Joystick axis values ​​and routines for capturing Joystick clicks
 * 
 */
void          input_init(){
    ads_init(false, false);
    buttons_init();
}


/**
 * @brief Returns the command generated by USB or keyboard
 * 
 * @return InputCommands 
 */
InputCommands input_get(){
    // USB commands
    switch(getchar_timeout_us(0)){
        case 'A':
        case 'a': return IN_CMD_LEFT;
        case 'D':
        case 'd': return IN_CMD_RIGHT;
        case 'W':
        case 'w': return IN_CMD_UP;
        case 'X':
        case 'x': return IN_CMD_DOWN;
        case 'S':
        case 's': return IN_CMD_PRESS;
    }

    // Joystick clciks
    if(button_n_clicks(BUTTON_JOYSTICK, CLEAR_ALL)) return IN_CMD_PRESS;

    last_x = ads_get(AD_JOYSTICK_X);
    last_y = ads_get(AD_JOYSTICK_Y);

    // joystick repetition time
    if(time_us_64() <= t0) return IN_CMD_NO_CMD;

    // Joystick commands, repetition time
    if(last_x < AD_VALUE_DOWN){
        t0 = time_us_64() + AD_SPEED_US;
        return IN_CMD_LEFT;
    }
    if(last_x > AD_VALUE_UP){
        t0 = time_us_64() + AD_SPEED_US;
        return IN_CMD_RIGHT;
    }

    if(last_y < AD_VALUE_DOWN){
        t0 = time_us_64() + AD_SPEED_US;
        return IN_CMD_DOWN;
    }
    if(last_y > AD_VALUE_UP){
        t0 = time_us_64() + AD_SPEED_US;
        return IN_CMD_UP;
    }

    return IN_CMD_NO_CMD;
}

/**
 * @brief Returns the last value read from the joystick's X axis
 * 
 * @return uint16_t (Last X axis value) 
 */
uint16_t      input_last_x(){
    return last_x;
}

/**
 * @brief Returns the last value read from the joystick's Y axis
 * 
 * @return uint16_t (Last Y axis value)
 */
uint16_t      input_last_y(){
    return last_y;
}