/**
 * @file    input.h
 * @author  Ricardo J. Furlan
 * @brief   Interface for input modules: USB or Mouse
 * @version 0.1
 * @date    2025-05-09 
 */
#ifndef INPUT_H
#define INPUT_H

typedef enum{
    IN_CMD_NO_CMD = 0,
    IN_CMD_UP,
    IN_CMD_DOWN,
    IN_CMD_LEFT,
    IN_CMD_RIGHT,
    IN_CMD_PRESS
} InputCommands;


/**
 * @brief Initializes: ADs for acquiring Joystick axis values ​​and routines for capturing Joystick clicks
 * 
 */
void          input_init();

/**
 * @brief Returns the command generated by USB or keyboard
 * 
 * @return InputCommands 
 */
InputCommands input_get();

/**
 * @brief Returns the last value read from the joystick's X axis
 * 
 * @return uint16_t (Last X axis value) 
 */
uint16_t      input_last_x();

/**
 * @brief Returns the last value read from the joystick's Y axis
 * 
 * @return uint16_t (Last Y axis value)
 */
uint16_t      input_last_y();


#endif // INPUT_H
